// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

type Area struct {
	ID          int32
	RegionID    int32
	CountryName string
	CountryCode string
	CurrencyID  int32
}

type Country struct {
	ID     int32
	AreaID int32
}

type Currency struct {
	ID   int32
	Name string
	Code string
}

type Region struct {
	ID   int32
	Name string
}
