// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
)

type TblUser struct {
	UserID       int32
	Email        string
	LoginID      string
	MobileNumber sql.NullString
	Password     string
	UserName     sql.NullString
	ChannelID    sql.NullInt32
	Otp          sql.NullString
	Mpin         sql.NullString
	RoleID       sql.NullInt32
	ApiUser      sql.NullBool
	Status       sql.NullString
}
