// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
)

type TblArea struct {
	AreaID   int32
	AreaName sql.NullString
	CityID   sql.NullInt32
}

type TblCity struct {
	CityID   int32
	CityName sql.NullString
	RegionID sql.NullInt32
}

type TblCountry struct {
	CountryID         int32
	CountryName       sql.NullString
	CountryCode       sql.NullString
	CallingCode       sql.NullString
	CountryAlphaCode3 sql.NullString
	Region            sql.NullString
	FlagUrl           sql.NullString
	NumMaxlength      sql.NullInt32
	NumMinlength      sql.NullInt32
	Status            sql.NullInt32
	CurrencyIDTemp    sql.NullInt32
}

type TblCurrency struct {
	CurrencyID   int32
	CurrencyName sql.NullString
	CurrencyCode sql.NullString
	CountryID    sql.NullInt32
}

type TblNumberSeries struct {
	NumberSeriesID int32
	OperatorID     sql.NullInt32
	NumberSeries   sql.NullInt32
	Status         sql.NullInt32
}

type TblRegion struct {
	RegionID   int32
	CountryID  sql.NullInt32
	RegionName sql.NullString
}

type TblServiceType struct {
	ServiceTypeID    int32
	ServiceTypeName  sql.NullString
	ServiceTypeCode  sql.NullString
	InsertedDate     sql.NullTime
	InsertedUser     sql.NullInt32
	LastModifiedDate sql.NullTime
	LastModifiedUser sql.NullInt32
	Remarks          sql.NullString
	Status           int32
	SyncCode1        sql.NullString
	SyncCodes        sql.NullString
}
