// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
)

type TblChannel struct {
	ChannelID        int32
	Address          sql.NullString
	AreaID           sql.NullInt32
	ChReferenceID    sql.NullInt32
	ChannelCode      sql.NullString
	ChannelType      sql.NullInt32
	CityID           sql.NullInt32
	CountryID        sql.NullInt32
	DateOfBirth      sql.NullTime
	DisplayName      sql.NullString
	Email            sql.NullString
	FirstName        sql.NullString
	GenderID         sql.NullInt32
	InsertedDate     sql.NullTime
	InsertedUser     sql.NullInt32
	Longitude        sql.NullFloat64
	LastModifiedDate sql.NullTime
	LastModifiedUser sql.NullInt32
	LastName         sql.NullString
	Latitude         sql.NullFloat64
	Level            sql.NullInt32
	MobileNumber     sql.NullString
	Pincode          sql.NullString
	RegionID         sql.NullInt32
	Remarks          sql.NullString
	Status           sql.NullInt32
	ProfileID        sql.NullInt32
	ChLevel          sql.NullInt32
	Password         sql.NullString
	CurrencyID       sql.NullInt32
	CurrencyName     sql.NullString
	CountryName      sql.NullString
	AreaName         sql.NullString
	CityName         sql.NullString
	RegionName       sql.NullString
	ProfileName      sql.NullString
	ChReferenceCode  sql.NullString
	ChReferenceName  sql.NullString
	Commission       sql.NullFloat64
	CommissionType   sql.NullInt32
	CommissionValue  sql.NullFloat64
	Dob              sql.NullString
	UserID           sql.NullInt32
	SalesManagerID   sql.NullInt32
	Imei             sql.NullString
	SerialNumber     sql.NullString
	SimNumber        sql.NullString
	CalcType         sql.NullInt32
	CatID            sql.NullInt32
	ClientName       sql.NullString
	ContactPerson    sql.NullString
	MarkupValue      sql.NullFloat64
	Mobile           sql.NullString
	CurrencyCode     sql.NullString
	StatusDesc       sql.NullString
}
