// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type TblArea struct {
	AreaID   int32
	AreaName pgtype.Text
	CityID   pgtype.Int4
}

type TblCity struct {
	CityID   int32
	CityName pgtype.Text
	RegionID pgtype.Int4
}

type TblCountry struct {
	CountryID         int32
	CountryName       pgtype.Text
	CountryCode       pgtype.Text
	CallingCode       pgtype.Text
	CountryAlphaCode3 pgtype.Text
	Region            pgtype.Text
	FlagUrl           pgtype.Text
	NumMaxlength      pgtype.Int4
	NumMinlength      pgtype.Int4
	Status            pgtype.Int4
	CurrencyIDTemp    pgtype.Int4
}

type TblCurrency struct {
	CurrencyID   int32
	CurrencyName pgtype.Text
	CurrencyCode pgtype.Text
	CountryID    pgtype.Int4
}

type TblRegion struct {
	RegionID   int32
	CountryID  pgtype.Int4
	RegionName pgtype.Text
}
