// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
)

type TblCountry struct {
	CountryID         int32
	CountryName       sql.NullString
	CountryCode       sql.NullString
	CallingCode       sql.NullString
	CountryAlphaCode3 sql.NullString
	Region            sql.NullString
	FlagUrl           sql.NullString
	NumMaxlength      sql.NullInt32
	NumMinlength      sql.NullInt32
	Status            sql.NullInt32
}

type TblOperator struct {
	OperatorID   int32
	OperatorName sql.NullString
	OperatorCode sql.NullString
	Status       sql.NullInt32
}

type TblProduct struct {
	ProductID           int32
	OperatorID          sql.NullInt32
	Price               sql.NullFloat64
	ProductName         sql.NullString
	ServiceTypeID       sql.NullInt32
	Validity            sql.NullInt32
	SyncProviderID      sql.NullInt32
	ProviderProductCode sql.NullString
	ShortDescription    sql.NullString
	Description         sql.NullString
	ProductCode         sql.NullString
	ServiceTypeTemp     sql.NullString
	ReceiveCurrencyName sql.NullString
	SendCurrencyName    sql.NullString
	SendPrice           sql.NullFloat64
	ServiceTypeName     sql.NullString
	InsertedDate        sql.NullTime
	InsertedUser        sql.NullInt32
	LastModifiedDate    sql.NullTime
	LastModifiedUser    sql.NullInt32
	Status              sql.NullInt32
	Remarks             sql.NullString
	ValidityTypeID      sql.NullInt32
	ProductImage        sql.NullString
	VoucherTemplate     sql.NullString
	ValidityDesc        sql.NullString
	Benefits            sql.NullString
	CurrencyName        sql.NullString
	LanguageCode        sql.NullString
	LanguageID          sql.NullInt32
	MaxPrice            sql.NullFloat64
	MaxSendPrice        sql.NullFloat64
	MoreDescription     sql.NullString
	OpParam1            sql.NullString
	OpParam2            sql.NullString
	OpParam3            sql.NullString
	OpParam4            sql.NullString
	OpParam5            sql.NullString
	ValidityPeriodIso   sql.NullString
	BenefitCodes        sql.NullString
	CurrencyID          sql.NullInt32
	SpCurrencyID        sql.NullInt32
	SpMaxPrice          sql.NullFloat64
	SpPrice             sql.NullFloat64
}

type TblVoucherPin struct {
	ID      int32
	PinCode sql.NullString
	Status  sql.NullInt32
}
